seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 15000
empirical_normalization: true
obs_groups: {}
clip_actions: null
save_interval: 100
experiment_name: magiclab_z1_12dof_velocity
run_name: p3_fine
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: 2026-05-08_07-09-14_p3_coarse_v2
load_checkpoint: model_10500.pt
class_name: OnPolicyRunner
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_obs_normalization: {}
  critic_obs_normalization: {}
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.01
  desired_kl: 0.016
  max_grad_norm: 0.5
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  rnd_cfg: null
  symmetry_cfg: null
